"use client";

import { Bell, ChefHat, LogOut, Ruler, Save, Shield, UserRound } from "lucide-react";
import { useState } from "react";

export default function AccountSettingsPage() {
  const [saved, setSaved] = useState(false);
  return <div className="p-4 md:p-8 xl:p-12"><div className="mx-auto max-w-5xl"><p className="eyebrow">Account settings</p><h1 className="mt-2 font-editorial text-5xl font-semibold md:text-6xl">Your kitchen defaults.</h1><p className="mt-4 text-sm text-ink/55">Update your profile, measurement system, pantry staples, and notifications.</p>{saved ? <div className="mt-6 rounded-2xl border border-olive/25 bg-olive/8 p-4 text-sm font-semibold text-olive">Settings saved.</div> : null}<div className="mt-10 grid gap-6 lg:grid-cols-[220px_1fr]"><nav className="space-y-2">{[[UserRound,"Profile"],[Ruler,"Measurements"],[ChefHat,"Kitchen & pantry"],[Bell,"Notifications"],[Shield,"Privacy"]].map(([Icon,label],i)=>{const I=Icon as typeof Bell;return <button key={label as string} className={`flex w-full items-center gap-3 rounded-2xl px-4 py-3 text-sm font-semibold ${i===0 ? "bg-ink text-paper" : "text-ink/55 hover:bg-white/40"}`}><I size={17}/>{label as string}</button>})}</nav><div className="space-y-6"><article className="card p-6"><p className="eyebrow">Profile</p><div className="mt-5 flex flex-col gap-5 sm:flex-row sm:items-center"><div className="grid h-20 w-20 place-items-center rounded-full bg-tomato font-editorial text-2xl font-semibold text-paper">LP</div><div><button className="btn-secondary">Change photo</button><p className="mt-2 text-xs text-ink/40">JPG, PNG, or WEBP.</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label><span className="mb-2 block text-xs font-semibold">Name</span><input className="field" defaultValue="Lukas Phimvongsa" /></label><label><span className="mb-2 block text-xs font-semibold">Email</span><input className="field" defaultValue="lukas@example.com" /></label><label><span className="mb-2 block text-xs font-semibold">Skill level</span><select className="field" defaultValue="Intermediate"><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></label><label><span className="mb-2 block text-xs font-semibold">Default units</span><select className="field" defaultValue="US customary"><option>US customary</option><option>Metric</option></select></label></div><button className="btn-primary mt-6" onClick={()=>setSaved(true)}><Save size={16}/> Save settings</button></article><article className="rounded-[1.75rem] border border-tomato/20 bg-tomato/5 p-6"><h2 className="font-editorial text-2xl font-semibold text-tomato">Account actions</h2><button className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-tomato"><LogOut size={15}/> Sign out</button></article></div></div></div></div>
}
