// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/app" | "/app/inbox" | "/app/parties" | "/app/parties/[partyId]" | "/app/parties/[partyId]/costs" | "/app/parties/[partyId]/guests" | "/app/parties/[partyId]/menu" | "/app/parties/[partyId]/recipes" | "/app/parties/[partyId]/recipes/[recipeId]" | "/app/parties/[partyId]/settings" | "/app/parties/[partyId]/shopping" | "/app/parties/[partyId]/timeline" | "/app/parties/new" | "/app/recipes" | "/app/recipes/[id]" | "/app/recipes/new" | "/app/settings" | "/auth/login" | "/invite/[token]" | "/onboarding"
type AppRouteHandlerRoutes = "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/" | "/app" | "/app/parties/[partyId]"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/app": {}
  "/app/inbox": {}
  "/app/parties": {}
  "/app/parties/[partyId]": { "partyId": string; }
  "/app/parties/[partyId]/costs": { "partyId": string; }
  "/app/parties/[partyId]/guests": { "partyId": string; }
  "/app/parties/[partyId]/menu": { "partyId": string; }
  "/app/parties/[partyId]/recipes": { "partyId": string; }
  "/app/parties/[partyId]/recipes/[recipeId]": { "partyId": string; "recipeId": string; }
  "/app/parties/[partyId]/settings": { "partyId": string; }
  "/app/parties/[partyId]/shopping": { "partyId": string; }
  "/app/parties/[partyId]/timeline": { "partyId": string; }
  "/app/parties/new": {}
  "/app/recipes": {}
  "/app/recipes/[id]": { "id": string; }
  "/app/recipes/new": {}
  "/app/settings": {}
  "/auth/callback": {}
  "/auth/login": {}
  "/invite/[token]": { "token": string; }
  "/onboarding": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/app": never
  "/app/parties/[partyId]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
