// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/app/inbox/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/inbox">> = Specific
  const handler = {} as typeof import("../../app/app/inbox/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app">> = Specific
  const handler = {} as typeof import("../../app/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/parties/[partyId]/costs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/parties/[partyId]/costs">> = Specific
  const handler = {} as typeof import("../../app/app/parties/[partyId]/costs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/parties/[partyId]/guests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/parties/[partyId]/guests">> = Specific
  const handler = {} as typeof import("../../app/app/parties/[partyId]/guests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/parties/[partyId]/menu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/parties/[partyId]/menu">> = Specific
  const handler = {} as typeof import("../../app/app/parties/[partyId]/menu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/parties/[partyId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/parties/[partyId]">> = Specific
  const handler = {} as typeof import("../../app/app/parties/[partyId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/parties/[partyId]/recipes/[recipeId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/parties/[partyId]/recipes/[recipeId]">> = Specific
  const handler = {} as typeof import("../../app/app/parties/[partyId]/recipes/[recipeId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/parties/[partyId]/recipes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/parties/[partyId]/recipes">> = Specific
  const handler = {} as typeof import("../../app/app/parties/[partyId]/recipes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/parties/[partyId]/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/parties/[partyId]/settings">> = Specific
  const handler = {} as typeof import("../../app/app/parties/[partyId]/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/parties/[partyId]/shopping/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/parties/[partyId]/shopping">> = Specific
  const handler = {} as typeof import("../../app/app/parties/[partyId]/shopping/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/parties/[partyId]/timeline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/parties/[partyId]/timeline">> = Specific
  const handler = {} as typeof import("../../app/app/parties/[partyId]/timeline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/parties/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/parties/new">> = Specific
  const handler = {} as typeof import("../../app/app/parties/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/parties/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/parties">> = Specific
  const handler = {} as typeof import("../../app/app/parties/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/recipes/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/recipes/[id]">> = Specific
  const handler = {} as typeof import("../../app/app/recipes/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/recipes/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/recipes/new">> = Specific
  const handler = {} as typeof import("../../app/app/recipes/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/recipes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/recipes">> = Specific
  const handler = {} as typeof import("../../app/app/recipes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/settings">> = Specific
  const handler = {} as typeof import("../../app/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/login">> = Specific
  const handler = {} as typeof import("../../app/auth/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/invite/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invite/[token]">> = Specific
  const handler = {} as typeof import("../../app/invite/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../app/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app">> = Specific
  const handler = {} as typeof import("../../app/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/parties/[partyId]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app/parties/[partyId]">> = Specific
  const handler = {} as typeof import("../../app/app/parties/[partyId]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
