-- Starter USD unit prices for common dinner-party ingredients.
-- Prices are rough averages for MVP estimates; AI/manual upserts can refine later.

insert into public.ingredient_prices (canonical_key, unit, price_per_unit, currency, source) values
  ('olive oil', 'cup', 4.50, 'USD', 'seed'),
  ('butter', 'cup', 3.20, 'USD', 'seed'),
  ('all purpose flour', 'cup', 0.35, 'USD', 'seed'),
  ('flour', 'cup', 0.35, 'USD', 'seed'),
  ('sugar', 'cup', 0.40, 'USD', 'seed'),
  ('brown sugar', 'cup', 0.55, 'USD', 'seed'),
  ('salt', 'tsp', 0.02, 'USD', 'seed'),
  ('black pepper', 'tsp', 0.08, 'USD', 'seed'),
  ('garlic', 'clove', 0.15, 'USD', 'seed'),
  ('onion', 'each', 0.80, 'USD', 'seed'),
  ('lemon', 'each', 0.70, 'USD', 'seed'),
  ('eggs', 'each', 0.40, 'USD', 'seed'),
  ('egg', 'each', 0.40, 'USD', 'seed'),
  ('chicken breast', 'lb', 4.50, 'USD', 'seed'),
  ('chicken thighs', 'lb', 3.80, 'USD', 'seed'),
  ('ground beef', 'lb', 5.50, 'USD', 'seed'),
  ('salmon', 'lb', 12.00, 'USD', 'seed'),
  ('shrimp', 'lb', 10.00, 'USD', 'seed'),
  ('pasta', 'lb', 1.80, 'USD', 'seed'),
  ('rice', 'cup', 0.45, 'USD', 'seed'),
  ('heavy cream', 'cup', 2.10, 'USD', 'seed'),
  ('milk', 'cup', 0.35, 'USD', 'seed'),
  ('parmesan', 'cup', 4.00, 'USD', 'seed'),
  ('mozzarella', 'lb', 5.50, 'USD', 'seed'),
  ('tomato', 'each', 0.75, 'USD', 'seed'),
  ('cherry tomatoes', 'cup', 2.50, 'USD', 'seed'),
  ('basil', 'cup', 1.50, 'USD', 'seed'),
  ('parsley', 'cup', 0.90, 'USD', 'seed'),
  ('spinach', 'cup', 0.80, 'USD', 'seed'),
  ('potato', 'each', 0.60, 'USD', 'seed'),
  ('potatoes', 'lb', 1.20, 'USD', 'seed'),
  ('carrot', 'each', 0.30, 'USD', 'seed'),
  ('carrots', 'lb', 1.10, 'USD', 'seed'),
  ('celery', 'stalk', 0.25, 'USD', 'seed'),
  ('bell pepper', 'each', 1.20, 'USD', 'seed'),
  ('mushroom', 'cup', 1.40, 'USD', 'seed'),
  ('mushrooms', 'lb', 4.00, 'USD', 'seed'),
  ('wine', 'cup', 2.50, 'USD', 'seed'),
  ('chicken stock', 'cup', 0.60, 'USD', 'seed'),
  ('vegetable stock', 'cup', 0.55, 'USD', 'seed'),
  ('soy sauce', 'tbsp', 0.10, 'USD', 'seed'),
  ('honey', 'tbsp', 0.25, 'USD', 'seed'),
  ('vanilla extract', 'tsp', 0.40, 'USD', 'seed'),
  ('baking powder', 'tsp', 0.05, 'USD', 'seed'),
  ('baking soda', 'tsp', 0.03, 'USD', 'seed')
on conflict (canonical_key) do nothing;
