-- Prefer weight-based USD/oz seeds so grocery costing stays coherent after
-- count/misc → oz conversion. Upsert overwrites prior seed rows for these keys.

insert into public.ingredient_prices (canonical_key, unit, price_per_unit, currency, source) values
  ('olive oil', 'oz', 0.55, 'USD', 'seed'),
  ('butter', 'oz', 0.40, 'USD', 'seed'),
  ('flour', 'oz', 0.08, 'USD', 'seed'),
  ('sugar', 'oz', 0.09, 'USD', 'seed'),
  ('brown sugar', 'oz', 0.10, 'USD', 'seed'),
  ('salt', 'oz', 0.05, 'USD', 'seed'),
  ('black pepper', 'oz', 1.10, 'USD', 'seed'),
  ('garlic', 'oz', 1.40, 'USD', 'seed'),
  ('onion', 'oz', 0.08, 'USD', 'seed'),
  ('lemon', 'oz', 0.25, 'USD', 'seed'),
  ('egg', 'oz', 0.23, 'USD', 'seed'),
  ('eggs', 'oz', 0.23, 'USD', 'seed'),
  ('bacon', 'oz', 0.55, 'USD', 'seed'),
  ('celery', 'oz', 0.10, 'USD', 'seed'),
  ('chicken broth', 'oz', 0.08, 'USD', 'seed'),
  ('chicken stock', 'oz', 0.08, 'USD', 'seed'),
  ('half and half', 'oz', 0.18, 'USD', 'seed'),
  ('heavy cream', 'oz', 0.25, 'USD', 'seed'),
  ('milk', 'oz', 0.05, 'USD', 'seed'),
  ('clam juice', 'oz', 0.35, 'USD', 'seed'),
  ('clams', 'oz', 0.90, 'USD', 'seed'),
  ('potatoes', 'oz', 0.08, 'USD', 'seed'),
  ('potato', 'oz', 0.08, 'USD', 'seed'),
  ('worcestershire sauce', 'oz', 0.40, 'USD', 'seed'),
  ('hot sauce', 'oz', 0.45, 'USD', 'seed'),
  ('bay leaf', 'oz', 8.00, 'USD', 'seed'),
  ('oregano', 'oz', 2.50, 'USD', 'seed'),
  ('thyme', 'oz', 2.80, 'USD', 'seed'),
  ('parsley', 'oz', 0.90, 'USD', 'seed'),
  ('paprika', 'oz', 1.80, 'USD', 'seed'),
  ('smoked paprika', 'oz', 2.20, 'USD', 'seed'),
  ('chicken bouillon', 'oz', 1.20, 'USD', 'seed'),
  ('pasta', 'oz', 0.12, 'USD', 'seed'),
  ('rice', 'oz', 0.08, 'USD', 'seed'),
  ('chicken breast', 'oz', 0.28, 'USD', 'seed'),
  ('ground beef', 'oz', 0.34, 'USD', 'seed'),
  ('salmon', 'oz', 0.75, 'USD', 'seed'),
  ('shrimp', 'oz', 0.65, 'USD', 'seed'),
  ('parmesan', 'oz', 0.80, 'USD', 'seed'),
  ('mozzarella', 'oz', 0.35, 'USD', 'seed'),
  ('tomato', 'oz', 0.12, 'USD', 'seed')
on conflict (canonical_key) do update
set
  unit = excluded.unit,
  price_per_unit = excluded.price_per_unit,
  source = excluded.source,
  updated_at = now();
